require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThemeParksController do

  # This should return the minimal set of attributes required to create a valid
  # ThemePark. As you add validations to ThemePark, be sure to
  # adjust the attributes here as well.
    let(:valid_attributes) { { "name" => "MyString", "description" => "MyText", "location" => "TheLocation", "rating" => "3" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThemeParksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all theme_parks as @theme_parks" do
      theme_park = ThemePark.create! valid_attributes
      get :index, {}, valid_session
      assigns(:theme_parks).should eq([theme_park])
    end
  end

  describe "GET show" do
    it "assigns the requested theme_park as @theme_park" do
      theme_park = ThemePark.create! valid_attributes
      get :show, {:id => theme_park.to_param}, valid_session
      assigns(:theme_park).should eq(theme_park)
    end
  end

  describe "GET new" do
    it "assigns a new theme_park as @theme_park" do
      get :new, {}, valid_session
      assigns(:theme_park).should be_a_new(ThemePark)
    end
  end

  describe "GET edit" do
    it "assigns the requested theme_park as @theme_park" do
      theme_park = ThemePark.create! valid_attributes
      get :edit, {:id => theme_park.to_param}, valid_session
      assigns(:theme_park).should eq(theme_park)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThemePark" do
        expect {
          post :create, {:theme_park => valid_attributes}, valid_session
        }.to change(ThemePark, :count).by(1)
      end

      it "assigns a newly created theme_park as @theme_park" do
        post :create, {:theme_park => valid_attributes}, valid_session
        assigns(:theme_park).should be_a(ThemePark)
        assigns(:theme_park).should be_persisted
      end

      it "redirects to the created theme_park" do
        post :create, {:theme_park => valid_attributes}, valid_session
        response.should redirect_to(ThemePark.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved theme_park as @theme_park" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThemePark.any_instance.stub(:save).and_return(false)
        post :create, {:theme_park => { "name" => "invalid value" }}, valid_session
        assigns(:theme_park).should be_a_new(ThemePark)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThemePark.any_instance.stub(:save).and_return(false)
        post :create, {:theme_park => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested theme_park" do
        theme_park = ThemePark.create! valid_attributes
        # Assuming there are no other theme_parks in the database, this
        # specifies that the ThemePark created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ThemePark.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => theme_park.to_param, :theme_park => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested theme_park as @theme_park" do
        theme_park = ThemePark.create! valid_attributes
        put :update, {:id => theme_park.to_param, :theme_park => valid_attributes}, valid_session
        assigns(:theme_park).should eq(theme_park)
      end

      it "redirects to the theme_park" do
        theme_park = ThemePark.create! valid_attributes
        put :update, {:id => theme_park.to_param, :theme_park => valid_attributes}, valid_session
        response.should redirect_to(theme_park)
      end
    end

    describe "with invalid params" do
      it "assigns the theme_park as @theme_park" do
        theme_park = ThemePark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThemePark.any_instance.stub(:save).and_return(false)
        put :update, {:id => theme_park.to_param, :theme_park => { "name" => "invalid value" }}, valid_session
        assigns(:theme_park).should eq(theme_park)
      end

      it "re-renders the 'edit' template" do
        theme_park = ThemePark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThemePark.any_instance.stub(:save).and_return(false)
        put :update, {:id => theme_park.to_param, :theme_park => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested theme_park" do
      theme_park = ThemePark.create! valid_attributes
      expect {
        delete :destroy, {:id => theme_park.to_param}, valid_session
      }.to change(ThemePark, :count).by(-1)
    end

    it "redirects to the theme_parks list" do
      theme_park = ThemePark.create! valid_attributes
      delete :destroy, {:id => theme_park.to_param}, valid_session
      response.should redirect_to(theme_parks_url)
    end
  end

end
